#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, you may
#       want to try and run the script with that shell.
#
#   (2) Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var.word}", "${var,}" etc;
#         * redirection with >, >>, >&, &>, /dev/null, etc;
#         * backtick "`...`" - backquotes
#         * test conditional expressions;
#         * variable assignment using printf %s with "..." quoting
#
#   Important for patching:
#
#   (1) You MUST use the $( ) construct (not backticks ` ` ) to do command
#       substitution, because this script file can be executed directly by a
#       POSIX shell and then the command substitution results will be
#       unavailable when the outer shell has already exited.
#
#   (2) We have to be careful to avoid running the shell's built-in cd command
#       which does not print anything to stdout in the most shells by default.
#       But we are not even relying on having cd in our $PATH.
#
##############################################################################

# We all agree that Java is a workaround.
if ! command -v java &> /dev/null
then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo ""
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# If there's Java home set we use it
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
else
    JAVACMD="java"
fi

if [ -z "$GRADLE_OPTS" ] ; then
    GRADLE_OPTS=""
fi

GRADLE_OPTS="$GRADLE_OPTS \"-Dorg.gradle.appname=$APP_BASE_NAME\""

exec "$JAVACMD" $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
